apiVersion: skaffold/v1beta7
kind: Config
build:
  artifacts:
    - image: frontend-image
      context: section_3/frontend
    - image: playerops-image
      context: section_3/playerops
    - image: stats-image
      context: section_3/stats
    - image: transfer-image
      context: section_3/transfer
  tagPolicy:
    sha256: {}
deploy:
  kubectl:
    manifests:
      - section_3/kubernetes-manifests/frontend.yaml
      - section_3/kubernetes-manifests/playerops.yaml
      - section_3/kubernetes-manifests/stats.yaml
      - section_3/kubernetes-manifests/transfer.yaml
profiles:
  - build: {}
    deploy: {}
    name: remote cluster
  - build: {}
    deploy: {}
    name: GKE
