apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: frontend-image
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
          - name: port
            value: "8080"
          - name: STATS_SERVICE_ADDR
            value: "stats-service:8081"
          - name: PLAYER_SERVICE_ADDR
            value: "playerops-service:8082"
          - name: TRANSFER_SERVICE_ADDR
            value: "transfer-service:8083"
          
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 8080

#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: frontend-external
#spec:
#  type: LoadBalancer
#  selector:
#    app: frontend-service
#  ports:
#  - port: 80
#    targetPort: 8080