apiVersion: apps/v1
kind: Deployment
metadata:
  name: playerops-deployment
spec:
  selector:
    matchLabels:
      app: playerops
  template:
    metadata:
      labels:
        app: playerops
    spec:
      containers:
      - name: playerops
        image: playerops-image
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8082

---
apiVersion: v1
kind: Service
metadata:
  name: playerops-service
spec:
  type: ClusterIP
  selector:
    app: playerops
  ports:
  - port: 8082
    targetPort: 8082
