apiVersion: apps/v1
kind: Deployment
metadata:
  name: transfer-deployment
spec:
  selector:
    matchLabels:
      app: transfer
  template:
    metadata:
      labels:
        app: transfer
    spec:
      containers:
      - name: transfer
        image: transfer-image
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8083
        volumeMounts:
        - name: service-key
          mountPath: /root/apps-microservices-68b9b8c44847.json
          subPath: apps-microservices-68b9b8c44847.json
      volumes:
      - name: service-key
        secret:
          secretName: firestore-secret
          items:
          - key: service_account_key
            path: apps-microservices-68b9b8c44847.json

---
apiVersion: v1
kind: Service
metadata:
  name: transfer-service
spec:
  type: ClusterIP
  selector:
    app: transfer
  ports:
  - port: 8083
    targetPort: 8083
